/*
 * sistema de locação de autos
 */
package br.com.autos.tela;

import br.com.autos.control.ControlFuncionario;
import br.com.autos.model.ModelFuncionario;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gilber
 */
public class TelaFuncionario extends javax.swing.JFrame {
    //instacia model
    ModelFuncionario modelFuncionario = new ModelFuncionario();
    //instancia control
    ControlFuncionario controlFuncionario = new ControlFuncionario();
    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
    initComponents();
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/autos/img/icPerson100.png")));
    carregarListaFuncionario();
    desabilitarCampos();
    desabilitarBotao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtFunMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtFunNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtFunLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFunCancelar = new javax.swing.JButton();
        btnFunSalvarALteraçao = new javax.swing.JButton();
        btnFunSalvar = new javax.swing.JButton();
        btnFunNovo = new javax.swing.JButton();
        edtFunSenha = new javax.swing.JPasswordField();
        edtFunConfirmaSenha = new javax.swing.JPasswordField();
        btnFunAvançar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFuncionario = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnFunExcluir = new javax.swing.JButton();
        btnFunAlterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnFunVoltar = new javax.swing.JButton();

        jTextField5.setText("jTextField5");

        setTitle("Cadastro Funcionario");

        jLabel1.setText("Matricula:");

        jLabel2.setText("Nome:");

        edtFunNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtFunNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Login:");

        edtFunLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtFunLoginActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirma Senha:");

        btnFunCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_cancel_24.png"))); // NOI18N
        btnFunCancelar.setText("Cancelar");
        btnFunCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunCancelarActionPerformed(evt);
            }
        });

        btnFunSalvarALteraçao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_update_24.png"))); // NOI18N
        btnFunSalvarALteraçao.setText("Alterar");
        btnFunSalvarALteraçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunSalvarALteraçaoActionPerformed(evt);
            }
        });

        btnFunSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_salve_24.png"))); // NOI18N
        btnFunSalvar.setText("Salvar");
        btnFunSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunSalvarActionPerformed(evt);
            }
        });

        btnFunNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_add_24.png"))); // NOI18N
        btnFunNovo.setText("Novo");
        btnFunNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnFunCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFunSalvarALteraçao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFunSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFunNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFunCancelar)
                    .addComponent(btnFunSalvarALteraçao)
                    .addComponent(btnFunSalvar)
                    .addComponent(btnFunNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edtFunSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtFunSenhaActionPerformed(evt);
            }
        });

        edtFunConfirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtFunConfirmaSenhaActionPerformed(evt);
            }
        });

        btnFunAvançar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon16/icFrente.png"))); // NOI18N
        btnFunAvançar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunAvançarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edtFunMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edtFunNome, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnFunAvançar))
                                    .addComponent(edtFunLogin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edtFunSenha)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(edtFunConfirmaSenha, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFunMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtFunNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFunLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtFunSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtFunConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnFunAvançar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        tabelFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelFuncionario);
        if (tabelFuncionario.getColumnModel().getColumnCount() > 0) {
            tabelFuncionario.getColumnModel().getColumn(0).setMinWidth(50);
            tabelFuncionario.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnFunExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_delete_24.png"))); // NOI18N
        btnFunExcluir.setText("Excluir");
        btnFunExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunExcluirActionPerformed(evt);
            }
        });

        btnFunAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_update_24.png"))); // NOI18N
        btnFunAlterar.setText("Alterar");
        btnFunAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunAlterarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/iconSelectROw24.png"))); // NOI18N
        jButton1.setText("selecione");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnFunExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFunAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFunExcluir)
                    .addComponent(btnFunAlterar)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        btnFunVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon16/icAtraz.png"))); // NOI18N
        btnFunVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnFunVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFunVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alterar/Excluir", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtFunSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtFunSenhaActionPerformed
        edtFunConfirmaSenha.requestFocus();
    }//GEN-LAST:event_edtFunSenhaActionPerformed

    private void btnFunVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunVoltarActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnFunVoltarActionPerformed

    private void btnFunAvançarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunAvançarActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(1);
        btnFunAlterar.setEnabled(false);
        btnFunCancelar.setEnabled(false);
    }//GEN-LAST:event_btnFunAvançarActionPerformed

    private void btnFunNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunNovoActionPerformed
        btnFunNovo.setEnabled(false);
        // habilitar os campos p/ entrada de dados
        habilitarCampos();
        //habilitar botão
        habilitarBotao();
        //focus
        edtFunNome.requestFocus();
    }//GEN-LAST:event_btnFunNovoActionPerformed

    private void btnFunSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunSalvarActionPerformed
        //metodo salvar funcionario
        cadastroFuncionario();      
    }//GEN-LAST:event_btnFunSalvarActionPerformed

    private void btnFunSalvarALteraçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunSalvarALteraçaoActionPerformed
       //
       alterarFuncionario();
        this.jTabbedPane1.setSelectedIndex(1);  
        btnFunCancelar.setEnabled(false);
        btnFunSalvarALteraçao.setEnabled(false);
    }//GEN-LAST:event_btnFunSalvarALteraçaoActionPerformed

    private void btnFunCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunCancelarActionPerformed
        // TODO add your handling code here:
        desabilitarBotao();
        desabilitarCampos();
        btnFunNovo.setEnabled(true);
    }//GEN-LAST:event_btnFunCancelarActionPerformed

    private void edtFunNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtFunNomeActionPerformed
        edtFunLogin.requestFocus();
    }//GEN-LAST:event_edtFunNomeActionPerformed

    private void edtFunLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtFunLoginActionPerformed
        // TODO add your handling code here:
        edtFunSenha.requestFocus();
    }//GEN-LAST:event_edtFunLoginActionPerformed

    private void edtFunConfirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtFunConfirmaSenhaActionPerformed
        btnFunSalvar.requestFocus();
    }//GEN-LAST:event_edtFunConfirmaSenhaActionPerformed

    private void btnFunExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunExcluirActionPerformed
        // TODO add your handling code here:
        excluirFuncionario();
        carregarListaFuncionario();
    }//GEN-LAST:event_btnFunExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        btnFunExcluir.setEnabled(true);
        btnFunAlterar.setEnabled(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFunAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunAlterarActionPerformed
        this.jTabbedPane1.setSelectedIndex(0);
        btnFunSalvarALteraçao.setEnabled(true);
        btnFunNovo.setEnabled(false);
        btnFunCancelar.setEnabled(true);
        btnFunSalvar.setEnabled(false);
        habilitarCampos();
        recuperarFuncionario();
    }//GEN-LAST:event_btnFunAlterarActionPerformed
     /**
     * metodo limpar campos
     */
    public void limparCampos(){
        edtFunMatricula.setText("");
        edtFunNome.setText("");
        edtFunLogin.setText("");
        edtFunSenha.setText("");
        edtFunConfirmaSenha.setText("");
    }
    /**
     * metodo para desabilitar campos
     */
    public void desabilitarCampos(){
        edtFunMatricula.setEnabled(false);
        edtFunNome.setEnabled(false);
        edtFunLogin.setEnabled(false);
        edtFunSenha.setEnabled(false);
        edtFunConfirmaSenha.setEnabled(false);
    }
    /**
     * Habilitar campos para entrar com os dados do funcionario
     */
    public void habilitarCampos(){
        edtFunMatricula.setText("Novo");
        edtFunMatricula.setEnabled(false);
        edtFunNome.setEnabled(true);
        edtFunLogin.setEnabled(true);
        edtFunSenha.setEnabled(true);
        edtFunConfirmaSenha.setEnabled(true);
        
    }
    /**
     * metodo para desabilitar botão
     */
    public void desabilitarBotao(){
        btnFunCancelar.setEnabled(false);
        btnFunSalvarALteraçao.setEnabled(false);
        btnFunSalvar.setEnabled(false);
        btnFunExcluir.setEnabled(false);
        btnFunAlterar.setEnabled(false);
    }
    /**
     * metodo habilitar botões
     */
    public void habilitarBotao(){
        btnFunCancelar.setEnabled(true);
        btnFunSalvarALteraçao.setEnabled(true);
        btnFunSalvar.setEnabled(true);
        btnFunExcluir.setEnabled(true);
        btnFunAlterar.setEnabled(true);
    }
    /**
     * metodo cadastro de funcionario no banco
     */
    public void cadastroFuncionario(){
        //declaração de variaveis
        String txtFunNome, txtFunLogin, txtFunSenha, txtConfirmaSenha;
        txtFunNome = edtFunNome.getText();
        txtFunLogin = edtFunLogin.getText();
        txtFunSenha = new String (edtFunSenha.getPassword());
        txtConfirmaSenha = new String (edtFunConfirmaSenha.getPassword());
        //verificar se campos estão preenchidos
            if(!txtFunNome.isEmpty()){
            if(!txtFunLogin.isEmpty()){
            if(!txtFunSenha.isEmpty()){
            if(!txtConfirmaSenha.isEmpty()){
            //verificar senha iguais
            if(txtFunSenha.equals(txtConfirmaSenha)){
                //setar os dados de entrada na classe model
            modelFuncionario.setFunNome(txtFunNome);
            modelFuncionario.setFunLogin(txtFunLogin);
            modelFuncionario.setSenha(txtFunSenha);
            boolean resultado = controlFuncionario.controlGetProcFuncionario(modelFuncionario);
            if(resultado==true){
                JOptionPane.showMessageDialog(this, "Funcionario cadastrado com sucesso!");
                //limpar campos
                limparCampos();
                //desabilitar campos
                desabilitarCampos();
                //desabilitar botao
                desabilitarBotao();
                btnFunNovo.setEnabled(true);
                carregarListaFuncionario();
            }
        }else{
            //caso campos esteja vazio avisar funcionario
            JOptionPane.showMessageDialog(rootPane, "As senha informada não são iguais!");
            habilitarCampos();
            edtFunNome.setText(txtFunNome);
            edtFunLogin.setText(txtFunLogin);
            btnFunNovo.setEnabled(false);
            edtFunSenha.requestFocus();
        }
            //
        }else{
            //caso campos esteja vazio avisar funcionario
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo Confirma Senha");
            habilitarCampos();
            habilitarBotao();
            btnFunNovo.setEnabled(false);
            edtFunNome.requestFocus();
        }
        }else{
            //caso campos esteja vazio avisar funcionario
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo Senha");
            habilitarCampos();
            habilitarBotao();
            btnFunNovo.setEnabled(false);
            edtFunSenha.requestFocus();
        }
        }else{
            //caso campos esteja vazio avisar funcionario p
            //para preencher campo login
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo Login");
            habilitarCampos();
            habilitarBotao();
            btnFunNovo.setEnabled(false);
            edtFunLogin.requestFocus();
        }
        }else{
           //caso campos esteja vazio avisar funcionario
            JOptionPane.showMessageDialog(this, "Preencha o campo Nome:");
            habilitarCampos();
            habilitarBotao();
            btnFunNovo.setEnabled(false);
            edtFunNome.requestFocus();
        }
    }
    /**
     * carregar tabela
     */
    public void carregarListaFuncionario(){
        ArrayList<ModelFuncionario> listarFuncionario = new ArrayList<>();
        listarFuncionario = controlFuncionario.controlGetListaFuncionario();
        DefaultTableModel tableModel = (DefaultTableModel) tabelFuncionario.getModel();
        tableModel.setNumRows(0);
        int cont = listarFuncionario.size();
        for(int i = 0; i < cont; i++){  
            tableModel.addRow(new Object[]{
                listarFuncionario.get(i).getFunMatricula(),
                listarFuncionario.get(i).getFunNome(),
                listarFuncionario.get(i).getFunLogin()
            });
        }
        
    }
    /**
     * recuper Funcionario na tabela
     */
    public void recuperarFuncionario(){
        //recebe a linha selecionada
        int linha = this.tabelFuncionario.getSelectedRow();
        //pegar a matricula do funcionario selecionado
        int funMatricula = (int) tabelFuncionario.getValueAt(linha, 0);
        try{
            //recuperar dados do banco de dados
            modelFuncionario = controlFuncionario.controlGetRecuperarFunId(funMatricula);
            //seta dados na interface
            this.edtFunMatricula.setText(String.valueOf(modelFuncionario.getFunMatricula()));
            this.edtFunNome.setText(modelFuncionario.getFunNome());
            this.edtFunLogin.setText(modelFuncionario.getFunLogin());
            this.edtFunSenha.setText(modelFuncionario.getSenha());
            this.edtFunConfirmaSenha.setText(modelFuncionario.getSenha());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Erro");
        }
        
    }
    /**
     * metodo alterar funcionario
     */
    public void alterarFuncionario(){
       //declaração de variaveis
        String txtFunNome, txtFunLogin, txtFunSenha, txtConfirmaSenha;
        int funMatricula = Integer.parseInt(edtFunMatricula.getText());
        txtFunNome = edtFunNome.getText();
        txtFunLogin = edtFunLogin.getText();
        txtFunSenha = new String (edtFunSenha.getPassword());
        txtConfirmaSenha = new String (edtFunConfirmaSenha.getPassword());
        //verificar se campos estão preenchidos
            if(!txtFunNome.isEmpty()){
            if(!txtFunLogin.isEmpty()){
            if(!txtFunSenha.isEmpty()){
            if(!txtConfirmaSenha.isEmpty()){
            //verificar senha iguais
            if(txtFunSenha.equals(txtConfirmaSenha)){
                //setar os dados de entrada na classe model
            modelFuncionario.setFunMatricula(funMatricula);
            modelFuncionario.setFunNome(txtFunNome);
            modelFuncionario.setFunLogin(txtFunLogin);
            modelFuncionario.setSenha(txtFunSenha);
            boolean resultado = controlFuncionario.controlGetUpdateFuncionario(modelFuncionario);
            if(resultado==true){
                JOptionPane.showMessageDialog(this, "Funcionario Alterado com sucesso!");
                //limpar campos
                limparCampos();
                //desabilitar campos
                desabilitarCampos();
                //desabilitar botao
                desabilitarBotao();
                btnFunNovo.setEnabled(true);
                carregarListaFuncionario();
                this.jTabbedPane1.setSelectedIndex(1);
            }{
                btnFunSalvarALteraçao.setEnabled(true);
                btnFunCancelar.setEnabled(true);
            }
        }else{
            //caso campos esteja vazio avisar funcionario
            JOptionPane.showMessageDialog(rootPane, "As senha informada não são iguais!");
            habilitarCampos();
            edtFunNome.setText(txtFunNome);
            edtFunLogin.setText(txtFunLogin);
            btnFunNovo.setEnabled(false);
            edtFunSenha.requestFocus();
        }
            //
        }else{
            //caso campos esteja vazio avisar funcionario
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo Confirma Senha");
            habilitarCampos();
            habilitarBotao();
            btnFunNovo.setEnabled(false);
            edtFunNome.requestFocus();
        }
        }else{
            //caso campos esteja vazio avisar funcionario
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo Senha");
            habilitarCampos();
            habilitarBotao();
            btnFunNovo.setEnabled(false);
            edtFunSenha.requestFocus();
        }
        }else{
            //caso campos esteja vazio avisar funcionario p
            //para preencher campo login
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo Login");
            habilitarCampos();
            habilitarBotao();
            btnFunNovo.setEnabled(false);
            edtFunLogin.requestFocus();
        }
        }else{
           //caso campos esteja vazio avisar funcionario
            JOptionPane.showMessageDialog(this, "Preencha o campo Nome:");
            habilitarCampos();
            habilitarBotao();
            btnFunNovo.setEnabled(false);
            edtFunNome.requestFocus();
        }
    }
    /**
     * metodo excluir funcionario
     * 
     */
    public void excluirFuncionario(){
        int linha = tabelFuncionario.getSelectedRow();
        String tNome = (String) tabelFuncionario.getValueAt(linha, 1);
        int codigo = (int) tabelFuncionario.getValueAt(linha, 0);
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o Funcionario: \n"
                +tNome+"?","Atenção",JOptionPane.YES_NO_OPTION);
        if(opcao==JOptionPane.OK_OPTION){
            boolean resultado = controlFuncionario.controlGetDeleteFuncionario(codigo);
            if(resultado == true){
                JOptionPane.showMessageDialog(this, "Funcionário Excluido com sucesso!");
                carregarListaFuncionario();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFunAlterar;
    private javax.swing.JButton btnFunAvançar;
    private javax.swing.JButton btnFunCancelar;
    private javax.swing.JButton btnFunExcluir;
    private javax.swing.JButton btnFunNovo;
    private javax.swing.JButton btnFunSalvar;
    private javax.swing.JButton btnFunSalvarALteraçao;
    private javax.swing.JButton btnFunVoltar;
    private javax.swing.JPasswordField edtFunConfirmaSenha;
    private javax.swing.JTextField edtFunLogin;
    private javax.swing.JTextField edtFunMatricula;
    private javax.swing.JTextField edtFunNome;
    private javax.swing.JPasswordField edtFunSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tabelFuncionario;
    // End of variables declaration//GEN-END:variables
}
