/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.autos.tela;

import br.com.autos.control.ControlCategoria;
import br.com.autos.model.ModelCategoria;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gilber
 */
public class TelaCategoria extends javax.swing.JFrame {
    //instancia da classe Modelo
    ModelCategoria modelCategoria = new ModelCategoria();
    //instanica da classe controle
    ControlCategoria controlCategoria = new ControlCategoria();
    /**
     * Creates new form TelaCliente
     */
    public TelaCategoria() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/autos/img/categoria48.png")));
        this.desabilitarCampos();
        this.desabilitarBotão();
        this.carregarListaCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edtCatCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edtCatClasse = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtCatPreco = new javax.swing.JTextField();
        edtCatDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCategoria = new javax.swing.JTable();
        btnSelectCategoria = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        edtCarPesquisar = new javax.swing.JTextField();
        btnCatPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCatNovo = new javax.swing.JButton();
        btnCatSalvar = new javax.swing.JButton();
        btnCatEditar = new javax.swing.JButton();
        btnCatExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setTitle("Cadastrar Categoria");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Codigo:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Classe");

        edtCatClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCatClasseActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Preço:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Descrição:");

        edtCatPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCatPrecoActionPerformed(evt);
            }
        });

        edtCatDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtCatDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCatDescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtCatCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCatPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(edtCatClasse)
                    .addComponent(edtCatDescricao))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edtCatCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edtCatClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCatPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edtCatDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Informações da Categoria");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Listar Categoria");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Classe", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCategoria);
        if (tabelaCategoria.getColumnModel().getColumnCount() > 0) {
            tabelaCategoria.getColumnModel().getColumn(0).setMinWidth(50);
            tabelaCategoria.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnSelectCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/iconSelectROw24.png"))); // NOI18N
        btnSelectCategoria.setText("Selecionar");
        btnSelectCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnSelectCategoria)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelectCategoria)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCatPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon16/ic_pesquisar_16.png"))); // NOI18N
        btnCatPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(edtCarPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCatPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(edtCarPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatPesquisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCatNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_add_24.png"))); // NOI18N
        btnCatNovo.setText("Novo");
        btnCatNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatNovoActionPerformed(evt);
            }
        });

        btnCatSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_salve_24.png"))); // NOI18N
        btnCatSalvar.setText("Salvar");
        btnCatSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatSalvarActionPerformed(evt);
            }
        });

        btnCatEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_update_24.png"))); // NOI18N
        btnCatEditar.setText("Editar");
        btnCatEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatEditarActionPerformed(evt);
            }
        });

        btnCatExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_delete_24.png"))); // NOI18N
        btnCatExcluir.setText("Excluir");
        btnCatExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/autos/icon24/ic_cancel_24.png"))); // NOI18N
        btnCancelar.setText("Cancel");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCatNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCatSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCatEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCatExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCatNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCatSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCatEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCatExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Ação");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatSalvarActionPerformed
        salvarCategoria();
        carregarListaCategoria();
    }//GEN-LAST:event_btnCatSalvarActionPerformed

    private void btnCatNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatNovoActionPerformed
        // TODO add your handling code here:
        habilitarCampos();
        habilitarBotões();
    }//GEN-LAST:event_btnCatNovoActionPerformed

    private void btnSelectCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCategoriaActionPerformed

        recuperarCategoria();
        habilitarCampos();
        habilitarBotões();
        btnCatSalvar.setEnabled(false);
    }//GEN-LAST:event_btnSelectCategoriaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        desabilitarCampos();
        desabilitarBotão();
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCatEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatEditarActionPerformed
       alterarCategoria();
    }//GEN-LAST:event_btnCatEditarActionPerformed

    private void btnCatExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatExcluirActionPerformed
        excluirCategoria();
    }//GEN-LAST:event_btnCatExcluirActionPerformed

    private void edtCatClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCatClasseActionPerformed
       edtCatPreco.requestFocus();
    }//GEN-LAST:event_edtCatClasseActionPerformed

    private void edtCatPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCatPrecoActionPerformed
        edtCatDescricao.requestFocus();
    }//GEN-LAST:event_edtCatPrecoActionPerformed

    private void edtCatDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCatDescricaoActionPerformed
        btnCatSalvar.requestFocus();
    }//GEN-LAST:event_edtCatDescricaoActionPerformed

    private void btnCatPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatPesquisarActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) this.tabelaCategoria.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela);
        this.tabelaCategoria.setRowSorter(sorter);
        String text = edtCarPesquisar.getText();
        sorter.setRowFilter(RowFilter.regexFilter(text, 1));
    }//GEN-LAST:event_btnCatPesquisarActionPerformed
/**
 * metodo para habilitar campos
 */
    public void habilitarCampos(){
    edtCatCodigo.setEnabled(false);
    edtCatClasse.setEnabled(true);
    edtCatPreco.setEnabled(true);
    edtCatDescricao.setEnabled(true);
}
    /**
     * metodo desabilitar campos
     */
    private void desabilitarCampos(){
    edtCatCodigo.setEnabled(false);
    edtCatClasse.setEnabled(false);
    edtCatPreco.setEnabled(false);
    edtCatDescricao.setEnabled(false);
    }
    /**
     * metodo habilitar botões
     */
    public void habilitarBotões(){
        btnCatNovo.setEnabled(false);
        btnCatSalvar.setEnabled(true);
        btnCatEditar.setEnabled(true);
        btnCatExcluir.setEnabled(true);
        btnCancelar.setEnabled(true);
    }
    /**
     * metodo desabilitar botao
     */
    private void desabilitarBotão(){
        btnCatSalvar.setEnabled(false);
        btnCatEditar.setEnabled(false);
        btnCatExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnCatNovo.setEnabled(true);
    }
    /**
     * limpar campos
     */
    public void limparCampos(){
        edtCatCodigo.setText("");
        edtCatClasse.setText("");
        edtCatPreco.setText("");
        edtCatDescricao.setText("");
    }
/**
 * metodo salvar categoria
 */
    public void salvarCategoria(){
        //atribuitos variaveis para receber os dados de entradas
        String txtClasse, txtDescricao;
        double preco;
        txtClasse = edtCatClasse.getText();
        preco = Double.parseDouble(edtCatPreco.getText());
        txtDescricao = edtCatDescricao.getText();
        //verificar campos
        if(!txtClasse.isEmpty()){
            if(preco>=0){
                if(!txtDescricao.isEmpty()){   
                    //
                    modelCategoria.setCatClasse(txtClasse);
                    modelCategoria.setCatPreco(preco);
                    modelCategoria.setCatDescricao(txtDescricao);
                    boolean resultado = controlCategoria.controlSalvarCategoria(modelCategoria);
                    if(resultado == true){
                        JOptionPane.showMessageDialog(this, "Categoria registrado com sucesso!");
                       limparCampos();
                       desabilitarCampos();
                       desabilitarBotão();
                       btnCatNovo.setEnabled(resultado);
                    }else{
                        limparCampos();
                        desabilitarCampos();
                        desabilitarBotão();
                    }
    }else{
            JOptionPane.showMessageDialog(this, "Preencha Descrição!");
        }
    }else{
            JOptionPane.showMessageDialog(this, "Preencha o campo Preço!");
        }
    }else{
            JOptionPane.showMessageDialog(this, "Preencha o campo Classe!");
        }}
    //
    /**
     * metodo carregar tabela
     */
    private void carregarListaCategoria(){
        ArrayList<ModelCategoria> listarCategoria = new ArrayList<>();
        listarCategoria = controlCategoria.controlGetListaCategoria();
        DefaultTableModel tableModel = (DefaultTableModel) tabelaCategoria.getModel();
        tableModel.setNumRows(0);
        int cont = listarCategoria.size();
        for(int i = 0; i < cont; i++){  
            tableModel.addRow(new Object[]{
                listarCategoria.get(i).getCatCodigo(),
                listarCategoria.get(i).getCatClasse(),
                listarCategoria.get(i).getCatPreco(),
                listarCategoria.get(i).getCatDescricao()
            });
        }
        
    }
    /**
     * metodo recuperar categoria na tabela
     */
    public void recuperarCategoria(){
        //recebe a linha selecionada
        int linha = this.tabelaCategoria.getSelectedRow();
        //pegar o codigo da categoria selecionado
        int catCodigo = (int) tabelaCategoria.getValueAt(linha, 0);
        try{
            //recuperar dados do banco de dados
            modelCategoria = controlCategoria.controlGetRecuperarCodigoCat(catCodigo);
            //seta dados na interface
            this.edtCatCodigo.setText(String.valueOf(modelCategoria.getCatCodigo()));
            this.edtCatClasse.setText(modelCategoria.getCatClasse());
            this.edtCatPreco.setText(String.valueOf(modelCategoria.getCatPreco()));
            this.edtCatDescricao.setText(modelCategoria.getCatDescricao());
           
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Erro"+ex);
        }
        
    }
    /**
     * alterar categoria
     */
    public void alterarCategoria(){
       //declaração de variaveis
        String txtCatClasse, txtCatDescricao;
        double preco;
        int catCodigo = Integer.parseInt(edtCatCodigo.getText());
        txtCatClasse = edtCatClasse.getText();
        preco = Double.parseDouble(edtCatPreco.getText());
        txtCatDescricao = edtCatDescricao.getText();
        //verificar se campos estão preenchidos
            if(!txtCatClasse.isEmpty()){
            if(preco>0){
            if(!txtCatDescricao.isEmpty()){
                //setar os dados de entrada na classe model
                modelCategoria.setCatCodigo(catCodigo);
                modelCategoria.setCatClasse(txtCatClasse);
                modelCategoria.setCatPreco(preco);
                modelCategoria.setCatDescricao(txtCatDescricao);
            boolean resultado = controlCategoria.controlAlterarCategoria(modelCategoria);
            if(resultado==true){
                JOptionPane.showMessageDialog(this, "alteração concluida com sucesso!");
                //limpar campos
                limparCampos();
                //desabilitar campos
                desabilitarCampos();
                //desabilitar botao
                desabilitarBotão();
                btnCatNovo.setEnabled(true);
                carregarListaCategoria();
            }
            //
        }else{
            //caso campos esteja vazio aviso
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo descrição");
            habilitarCampos();
            habilitarBotões();
            btnCatNovo.setEnabled(false);
            edtCatDescricao.requestFocus();
        }
        }else{
            //caso campos esteja vazio aviso
            //para preencher campo Preço
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo Preço");
            habilitarCampos();
            habilitarBotões();
            btnCatNovo.setEnabled(false);
            edtCatPreco.requestFocus();
        }
        }else{
           //caso campos esteja vazio aviso
            JOptionPane.showMessageDialog(this, "Preencha o campo Classe:");
            habilitarCampos();
            habilitarBotões();
            btnCatNovo.setEnabled(false);
            edtCatClasse.requestFocus();
        }
    }
    //excluir categoria
    
    public void excluirCategoria(){
        int linha = tabelaCategoria.getSelectedRow();
        String tCategoria = (String) tabelaCategoria.getValueAt(linha, 1);
        int codigo = (int) tabelaCategoria.getValueAt(linha, 0);
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir a Categoria: \n"
                +tCategoria+"?","Atenção",JOptionPane.YES_NO_OPTION);
        if(opcao==JOptionPane.OK_OPTION){
            boolean resultado = controlCategoria.controlExcluirCategoria(codigo);
            if(resultado == true){
                JOptionPane.showMessageDialog(this, "categoria Excluida com sucesso!");
                carregarListaCategoria();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCatEditar;
    private javax.swing.JButton btnCatExcluir;
    private javax.swing.JButton btnCatNovo;
    private javax.swing.JButton btnCatPesquisar;
    private javax.swing.JButton btnCatSalvar;
    private javax.swing.JButton btnSelectCategoria;
    private javax.swing.JTextField edtCarPesquisar;
    private javax.swing.JTextField edtCatClasse;
    private javax.swing.JTextField edtCatCodigo;
    private javax.swing.JTextField edtCatDescricao;
    private javax.swing.JTextField edtCatPreco;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCategoria;
    // End of variables declaration//GEN-END:variables

   
}
